name: videocall
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  agora_rtc_engine: ^4.2.2
  auto_size_text: ^3.0.0
  cached_network_image: ^3.0.0
  cloud_firestore: ^1.0.0
  cupertino_icons: ^1.0.0
  firebase_auth: ^2.0.0
  firebase_core: ^1.10.0
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.0.0
  get: ^4.1.4
  getwidget: ^2.0.4
  google_sign_in: ^5.3.0
  http: ^0.13.0
  image: ^3.0.8
  image_picker: ^0.6.5
  intl: ^0.17.0
  js: ^0.6.2
  package_info: ^0.4.3+2
  permission_handler: ^8.2.6
  provider: ^6.0.1
  share: ^0.6.5+4
  shimmer: ^2.0.0
  simple_animations: ^3.1.1
  webfeed: ^0.7.0
  webview_flutter: ^1.0.7

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  rename: ^2.0.1
flutter_icons:
  android: true
  ios: false
  image_path: "assets/zoom_icon.png"

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/icon/
  uses-material-design: true
